version: '3'

name: homelib

services:

  node:
    build: .
    image: homelib-node-app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - userdef-net
    restart: on-failure

  postgres:
    build: ./database
    image: homelib-postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - userdef-net
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data

volumes:
  pg-data:


networks:
  userdef-net:
    driver: bridge
    name: node-net
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1


